config/routes.rb
Rails.application.routes.draw do

  get 'confirmations/show'

  scope "(:locale)", locale: /en|pt/ do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
    resources :user_sessions, only: [:create, :new, :destroy]
  end

  resource :confirmation, only: [:show]

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'

end

  #   end

app/models/room.rb
class Room < ActiveRecord::Base
	extend FriendlyId

	has_many :reviews, dependent: :destroy
	has_many :reviewed_rooms, through: :reviews, source: :room
	belongs_to :user

	validates_presence_of :title, :slug

	mount_uploader :picture, PictureUploader
	friendly_id :title, use: [:slugged, :history]

	def complete_name
		"#{title}, #{location}"
	end

	def self.most_recent
		order(created_at: :desc)
	end

	def self.search(query)
		if query.present?
			if ENV['RAILS_ENV'] == 'production'
				where(['location ILIKE :query OR title ILIKE :query OR description ILIKE :query',
				query: "%#{query}%"])
			else
				where(['location LIKE :query OR title LIKE :query OR description LIKE :query',
				query: "%#{query}%"])
			end
		else
			all
		end
	end

	def to_param
		"#{id}-#{title.parameterize}"
	end
end

app/controllers/rooms/base_controller.rb
class Rooms::BaseController < ApplicationController
	before_filter :require_authentication

	private

	def room
		@room ||= Room.find(params[:room_id])
	end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < Rooms::BaseController

	def create
		review = room.reviews.find_or_initialize_by(user_id: current_user.id)
		review.update!(reviews_params)
		head :ok
	end

	def update
		create
	end

	private

	def reviews_params
		params.require(:review).permit(:points)
	end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  PER_PAGE = 5

  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_room, only: [:show]
  before_action :set_users_room, only: [:edit, :update, :destroy]

  def index
    @search_query = params[:q]
    # O método #map, de coleções, retornará um novo Array contendo o resultado do bloco.
    # Dessa forma, para cada quarto, retornaremos o presenter equivalente.
    rooms = Room.search(@search_query).most_recent.paginate(page: params[:page], per_page: PER_PAGE)
    @rooms = RoomCollectionPresenter.new(rooms, self)
  end

  def show
    if user_signed_in?
      @user_review = @room.reviews.find_or_initialize_by(user_id: current_user.id)
    end
  end

  def new
    @room = current_user.rooms.build
  end

  def edit
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render action: :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render action: :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      room_model = Room.friendly.find_by(id: params[:id])
      @room = RoomPresenter.new(room_model, self)
    end

    def set_users_room
      @room = current_user.rooms.friendly.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description, :picture)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper

	def belongs_to_user(room)
		user_signed_in? && is_current_user?(room.user)
	end

end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('general.form_error')%></h2>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  <div>
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <%= error_tag @room, :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    <% room.stars.times do %>
      <%= fa_icon 'star' %>
    <% end %>

    <% (room.review_points.max - room.stars).times do %>
      <%= fa_icon 'star-o' %>
    <% end %>

    <%= t '.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point  %>
      <%= f.label :points, value: point do %>
        <%= fa_icon 'star' %>
      <% end %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% else %>
  <span class="login_required">
    <%= t('.login_to_review') %>
  </span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <h2><%= link_to highlight(room.title, @search_query), room.route %></h2>
  <%= render partial: 'review', locals: {room: room} %>

  <span class="created">
    <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
  </span>
  <p>
    <span class="location">
      <%= link_to highlight(room.location || t('.location'), @search_query), "https://maps.google.com/?q=#{room.location}", target: :blank %>
    </span>
  </p>
  <div class="room-description">
    <%= link_to(image_tag(room.thumb_url),room.picture_url) if room.has_picture? %>
    <p><%= highlight(room.description || '', @search_query) %></p>
  </div>
  <% if belongs_to_user(room) %>
    <ul>
      <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
      <li><%= link_to t('.destroy'), room_path(room.route), method: :delete, data: { confirm: t('dialogs.destroy') } %></li>
    </ul>
  <% end %>
</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
	<%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>
<h1>
	<% if @search_query.present? %>
		<%= t '.search_results' %>
	<% else %>
		<%= t '.title' %>
	<% end %>
</h1>

<% if @rooms.rooms.present? %>
	<%= render @rooms %>
	<div class="center">
		<%= will_paginate @rooms %>
	</div>
<% elsif @search_query.present? %>
	<br/><p><%= t('.search_no_results') %></p>
<% else %>
	<br/><p><%= t('.no_rooms') %></p>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>